### ISSUE TITLE
Prow CI: Upgrade config not using predefined steps

### ISSUE THREAD

**Issue by kpouget** [openshift-psap/ci-artifacts#137]
Currently, the cluster upgrade testing is performed "manually" in the [cluster_upgrade_to_image](https://github.com/openshift-psap/ci-artifacts/blob/master/roles/cluster_upgrade_to_image/tasks/main.yml) role. 

This simple playbook only waits for the end of the upgrade, but doesn't perform any other kind of test.

The reason for this choice is that 
1. the Prow CI steps for upgrading the cluster do not support running custom repository tests, which is mandatory for the GPU Operator (entitlement, installation of dependency, initial deployment and validation of GPU Operator).
2. we wanted to be able to validate rapidly NVIDIA implementation of the cluster upgrade support.

In the future, it would be important to move to a proper CI upgrade step.

**Comment by kpouget** [comment]
From discussion with the testplatform team:

> that won't verify distruption. I think you want `openshift-e2e-test` with `TEST_TYPE=upgrade`

```
    test:
    - ref: openshift-e2e-test
    dependencies:
      OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: "release:initial"
      OPENSHIFT_UPGRADE_RELEASE_IMAGE_OVERRIDE: "release:latest"
    env:
      TEST_TYPE: upgrade
      TEST_SUITE: ""
      TEST_UPGRADE_OPTIONS: ""
      DELETE_MC: "false"
```
==> I (@kpouget ) think that this cannot work because of point 1 in the issue description
