### ISSUE TITLE
set_scale.sh: cannot specify the source machineset

### ISSUE THREAD

**Issue by kpouget** [openshift-psap/ci-artifacts#163]
Currently, `./toolbox/cluster/set_scale.sh` cannot be customized to decide which `MachineSet` will be used to derive the new MachineSet:

```
- name: Get the names of an existing worker machinesets (of any instance type)
  command:
    oc get machinesets -n openshift-machine-api -o
    jsonpath='{range .items[?(@.spec.template.metadata.labels.machine\.openshift\.io/cluster-api-machine-role=="worker")]}{.metadata.name}{"\n"}{end}'
  register: oc_get_machinesets
  failed_when: not oc_get_machinesets.stdout
```

it would be nice to have the ability to easily override `oc_get_machinesets.stdout` to specify which machineset to use as a base.

Quick and dirty example of what I did to work around that:
```
- name: Get the names of an existing worker machinesets (of any instance type)
  command:
    echo kpouget-20210519-kf6rn-worker-eu-central-1b
  register: oc_get_machinesets
  failed_when: not oc_get_machinesets.stdout
```

The reason for that is that the instance-type I want isn't available in `eu-central-1a`, only in `1b`
